#!/usr/bin/env python3
# https://github.com/AlvifSandana/xorencryption/
from re import S
import sys
import math


# Notworking yet
s = sys.stdin.readlines()
s = s[0].rstrip()
lst_num = [ord(i) for i in s]


s2 = ''.join(str(lst_num))
print(type(s2))
print(s2)